/*
 * UART_Pbcfg.c
 *
 *  Created on: Oct 12, 2019
 *      Author: Mohammed
 */


#include "UART_Pbcfg.h"



//UART_cfg_t UART = {USART MODE,COMMUNICATION MODEL,DATA SIZE,PARITY,STOP PATTERN,TRANSMISSION SPEED,INTERRUPT,CLK EDGE};
const UART_cfg_t UART = {ASYNCHRONOUS,P2P,EIGHT_BITS,ODD,BIT,NORMAL_SPEED,INTERRUPT,NA};

